import { Router } from "express";
import crypto from "node:crypto";
import { prisma } from "../db/client.js";
import { researchSignal } from "../services/researchService.js";
import { persistResearchGraph } from "../services/researchGraphService.js";
import { buildResearchMemory, answerResearchQuestion, resolveResearchConflict, summarizeResearchMetrics } from "../services/researchMemoryService.js";
import { buildSetupSuggestions, validateSetup } from "../services/setupService.js";
import { publishFacebookReel } from "../services/facebookService.js";

const router = Router();
const researchJobs = new Map();
const MAX_RESEARCH_ACTIVITY = 100;
function normalizeRenderUrl(renderUrl) { if (!renderUrl) return null; return String(renderUrl).replace(/^\/api\/render-files\/projects\//, "/api/render-files/"); }
function publicProject(project, job) { return { id: project.id, signalId: project.signalId, title: project.title, status: project.status, renderUrl: normalizeRenderUrl(project.renderUrl), durationSeconds: project.durationSeconds == null ? null : Number(project.durationSeconds), cuts: project.cuts ?? null, seoCaption: project.seoCaption || null, setup: project.scriptLengthSeconds ? { length: project.scriptLengthSeconds, framework: project.selectedFramework, tone: project.tone, audienceLevel: project.audienceLevel } : null, research: project.researchSummary ? { summary: project.researchSummary, sources: project.researchSources || [], monetizationFlags: project.monetizationFlags || [], deepResearch: project.researchSources?.research_metrics || null } : null, researchStatus: job?.status || (project.researchSummary ? "ready" : project.status === "researching" ? "researching" : "ready"), researchProgress: Number(job?.progress ?? (project.researchSummary ? 100 : 0)), researchStageLabel: job?.label || null, researchStageDetail: job?.detail || null, error: job?.error || null }; }
function appendActivity(projectId, activity) { const job = researchJobs.get(projectId) || {}; const entry = { id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, at: new Date().toISOString(), ...activity }; const activities = [...(job.activities || []), entry].slice(-MAX_RESEARCH_ACTIVITY); researchJobs.set(projectId, { ...job, activities }); }
async function persistSearchSignal(signal) { if (signal.id && !String(signal.id).startsWith("search-")) return prisma.signal.findUnique({ where: { id: signal.id } }); if (!signal.sourceUrl || !signal.title) return null; const existing = await prisma.signal.findFirst({ where: { sourceUrl: signal.sourceUrl } }); if (existing) return existing; return prisma.signal.create({ data: { origin: "search", sourceType: signal.sourceType || "brave", sourceReliability: signal.sourceReliability || "general_web", searchQuery: signal.searchQuery || null, rank: signal.rank ?? null, category: signal.category || "TECHNOLOGY", heatPct: signal.heatPct || null, heatScore: signal.heatScore ?? null, title: String(signal.title).slice(0, 255), description: signal.description || null, whyReasoning: signal.whyReasoning || "Selected from live search results.", sourceName: signal.sourceName || null, sourceUrl: signal.sourceUrl, rawContent: signal.rawContent || null, status: "used" } }); }
async function runResearch(projectId, signal) {
  const setJob = (status, progress, label, detail) => researchJobs.set(projectId, { ...(researchJobs.get(projectId) || {}), status, progress, label, detail });
  setJob("planning", 5, "Planning the research", "Breaking the topic into evidence, mechanism, data, recent developments, and counter-evidence questions.");
  appendActivity(projectId, { type: "research.started", message: "Deep research job started." });
  try {
    const brief = await researchSignal(signal, { onProgress: (stage, progress) => { const labels = { planning: ["Planning the research", "Defining the questions Helix needs to answer before synthesis."], discovering: ["Discovering sources", "Searching academic, institutional, news, and independent evidence."], reading: ["Reading sources", "Opening selected sources and extracting their available evidence."], verifying: ["Verifying evidence", "Comparing claims, source quality, and conflicting findings."], synthesizing: ["Synthesizing findings", "Building an evidence-backed research intelligence brief."], ready: ["Research brief ready", "The evidence-backed brief is ready for guided setup."] }; const [label, detail] = labels[stage] || [stage, "Helix is working through the evidence pipeline."]; setJob(stage, progress, label, detail); }, onActivity: (activity) => appendActivity(projectId, activity) });
    await prisma.project.update({ where: { id: projectId }, data: { researchSummary: `${brief.executive_summary || brief.mechanism_summary || ""}\n\n${(brief.key_facts || []).map((fact) => `• ${fact}`).join("\n")}`.trim(), researchSources: { ...(brief), sources: brief.sources || [] }, monetizationFlags: brief.monetization_flags || [], suggestedFramework: brief.recommended_framework || null, suggestedLengthSeconds: brief.recommended_length_seconds || null, suggestedTone: brief.recommended_tone || null, status: "setup" } });
    await persistResearchGraph(projectId, brief, { status: "completed" });
    appendActivity(projectId, { type: "research.corpus_persisted", message: "Research corpus persisted for downstream Storyboard and AI workflows." });
    setJob("ready", 100, "Research brief ready", "The evidence-backed brief is ready for guided setup.");
  } catch (error) {
    console.error(`[research] Project ${projectId} failed:`, error);
    appendActivity(projectId, { type: "research.failed", status: "error", message: error.message || "Research failed." });
    const existing = researchJobs.get(projectId) || {}; setJob("error", existing.progress || 0, "Research failed", "Helix could not complete the evidence check."); researchJobs.set(projectId, { ...researchJobs.get(projectId), error: error.message || "Research failed." }); await prisma.project.update({ where: { id: projectId }, data: { status: "researching" } }).catch(() => {});
  }
}

router.get("/", async (req, res) => { try { const userId = req.user.id; const projects = await prisma.project.findMany({ where: { userId }, orderBy: { createdAt: "desc" }, take: 100, include: { signal: { select: { category: true, sourceName: true, sourceType: true } }, _count: { select: { scenes: true, exports: true } } } }); res.json({ projects: projects.map((project) => ({ id: project.id, title: project.title || project.signal?.sourceName || "Untitled research", status: project.status, createdAt: project.createdAt, updatedAt: project.updatedAt || project.createdAt, durationSeconds: project.durationSeconds == null ? null : Number(project.durationSeconds), cuts: project.cuts ?? project._count.scenes ?? 0, renderUrl: normalizeRenderUrl(project.renderUrl), category: project.signal?.category || "TECHNOLOGY", sourceName: project.signal?.sourceName || "", sourceType: project.signal?.sourceType || "", researchReady: Boolean(project.researchSummary), setupReady: Boolean(project.scriptLengthSeconds && project.selectedFramework), storyboardReady: project._count.scenes > 0, narrationReady: project._count.scenes > 0 && project.status !== "researching", exportCount: project._count.exports })) }); } catch (error) { console.error("GET /api/projects failed:", error); res.status(500).json({ error: "Failed to load research history." }); } });
router.post("/", async (req, res) => { try { const signalInput = req.body?.signal; const signalId = req.body?.signalId; let signal = signalId ? await prisma.signal.findUnique({ where: { id: signalId } }) : null; if (!signal && signalInput) signal = await persistSearchSignal(signalInput); if (!signal) return res.status(404).json({ error: "Signal not found. Provide signalId or the selected search signal." }); const project = await prisma.project.create({ data: { id: crypto.randomUUID(), userId: req.user.id, signalId: signal.id, title: signal.title, status: "researching" } }); researchJobs.set(project.id, { status: "queued", progress: 0, label: "Starting deep research", detail: "Preparing the evidence pipeline.", activities: [] }); void runResearch(project.id, signal); res.status(202).json({ project: publicProject(project, researchJobs.get(project.id)) }); } catch (error) { console.error("POST /api/projects failed:", error); res.status(500).json({ error: "Failed to create research project." }); } });
router.get("/:id", async (req, res) => { try { const project = await prisma.project.findUnique({ where: { id: req.params.id } }); if (!project) return res.status(404).json({ error: "Project not found." }); res.json({ project: publicProject(project, researchJobs.get(project.id)) }); } catch (error) { console.error("GET /api/projects/:id failed:", error); res.status(500).json({ error: "Failed to load project." }); } });
router.get("/:id/research", async (req, res) => { try { const project = await prisma.project.findUnique({ where: { id: req.params.id } }); if (!project) return res.status(404).json({ error: "Project not found." }); res.json({ project: publicProject(project, researchJobs.get(project.id)) }); } catch (error) { console.error("GET /api/projects/:id/research failed:", error); res.status(500).json({ error: "Failed to load research status." }); } });
router.post("/:id/research/retry", async (req, res) => { try { const project = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.user.id } }); if (!project) return res.status(404).json({ error: "Project not found." }); if (project.researchSummary || project.status !== "researching") return res.status(409).json({ error: "This research project is not eligible for retry." }); const existing = researchJobs.get(project.id); if (existing && !["error", "stopped"].includes(existing.status)) return res.status(409).json({ error: "Research is already running." }); const signal = await prisma.signal.findUnique({ where: { id: project.signalId } }); if (!signal) return res.status(404).json({ error: "Research signal not found." }); researchJobs.set(project.id, { status: "queued", progress: 0, label: "Retrying deep research", detail: "Restarting the evidence pipeline from the beginning.", activities: [{ id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, at: new Date().toISOString(), type: "research.retry_started", message: "Manual research retry started." }] }); void runResearch(project.id, signal); res.status(202).json({ project: publicProject(project, researchJobs.get(project.id)) }); } catch (error) { console.error(`POST /api/projects/${req.params.id}/research/retry failed:`, error); res.status(500).json({ error: "Failed to retry research." }); } });
router.get("/:id/research/activity", async (req, res) => { try { const project = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.user.id }, select: { id: true, status: true } }); if (!project) return res.status(404).json({ error: "Project not found." }); const job = researchJobs.get(project.id); res.json({ projectId: project.id, status: job?.status || (project.status === "researching" ? "researching" : "ready"), progress: Number(job?.progress ?? (project.status === "researching" ? 0 : 100)), activities: job?.activities || [] }); } catch (error) { console.error(`GET /api/projects/${req.params.id}/research/activity failed:`, error); res.status(500).json({ error: "Failed to load research activity." }); } });
router.get("/:id/research/graph", async (req, res) => { try { const project = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.user.id }, select: { id: true } }); if (!project) return res.status(404).json({ error: "Project not found." }); const session = await prisma.researchSession.findFirst({ where: { projectId: project.id }, orderBy: { createdAt: "desc" }, include: { plan: true, sources: { orderBy: { sourceIndex: "asc" } }, evidence: { orderBy: { evidenceIndex: "asc" } }, claims: { orderBy: { claimIndex: "asc" }, include: { verification: true, sourceLinks: { include: { source: true } }, evidenceLinks: { include: { evidence: true } } } }, conflicts: { orderBy: { createdAt: "asc" } } } }); if (!session) return res.status(404).json({ error: "Research graph is not available yet." }); res.json({ session }); } catch (error) { console.error(`GET /api/projects/${req.params.id}/research/graph failed:`, error); res.status(500).json({ error: "Failed to load the research evidence graph." }); } });
router.get("/:id/research/memory", async (req, res) => { try { const project = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.user.id }, select: { id: true } }); if (!project) return res.status(404).json({ error: "Project not found." }); const session = await prisma.researchSession.findFirst({ where: { projectId: project.id }, orderBy: { version: "desc" }, include: { plan: true, sources: { orderBy: { sourceIndex: "asc" } }, evidence: { orderBy: { evidenceIndex: "asc" } }, claims: { orderBy: { claimIndex: "asc" }, include: { verification: true, sourceLinks: { include: { source: true } }, evidenceLinks: { include: { evidence: true } } } }, conflicts: { orderBy: { createdAt: "asc" } } } }); if (!session) return res.status(404).json({ error: "Research memory is not available yet." }); res.json({ memory: buildResearchMemory(session) }); } catch (error) { console.error(`GET /api/projects/${req.params.id}/research/memory failed:`, error); res.status(500).json({ error: "Failed to load research memory." }); } });
router.get("/:id/research/metrics", async (req, res) => { try { const project = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.user.id }, select: { id: true } }); if (!project) return res.status(404).json({ error: "Project not found." }); const session = await prisma.researchSession.findFirst({ where: { projectId: project.id }, orderBy: { version: "desc" }, include: { claims: { include: { verification: true } }, sources: true, evidence: true, conflicts: true } }); if (!session) return res.status(404).json({ error: "Research metrics are not available yet." }); res.json({ metrics: summarizeResearchMetrics(session) }); } catch (error) { console.error(`GET /api/projects/${req.params.id}/research/metrics failed:`, error); res.status(500).json({ error: "Failed to load research metrics." }); } });
router.post("/:id/research/follow-up", async (req, res) => { try { const project = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.user.id }, select: { id: true } }); if (!project) return res.status(404).json({ error: "Project not found." }); const session = await prisma.researchSession.findFirst({ where: { projectId: project.id }, orderBy: { version: "desc" }, include: { plan: true, sources: { orderBy: { sourceIndex: "asc" } }, evidence: { orderBy: { evidenceIndex: "asc" } }, claims: { orderBy: { claimIndex: "asc" }, include: { verification: true, sourceLinks: { include: { source: true } }, evidenceLinks: { include: { evidence: true } } } }, conflicts: { orderBy: { createdAt: "asc" } } } }); if (!session) return res.status(404).json({ error: "Research memory is not available yet." }); const question = String(req.body?.question || "").trim(); if (!question) return res.status(400).json({ error: "A follow-up question is required." }); res.json({ question, grounded: true, ...answerResearchQuestion(session, question) }); } catch (error) { console.error(`POST /api/projects/${req.params.id}/research/follow-up failed:`, error); res.status(500).json({ error: "Failed to answer the research follow-up." }); } });
router.post("/:id/research/conflicts/:conflictId/resolve", async (req, res) => { try { const project = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.user.id }, select: { id: true } }); if (!project) return res.status(404).json({ error: "Project not found." }); const conflict = await prisma.researchConflict.findFirst({ where: { id: req.params.conflictId, session: { projectId: project.id } } }); if (!conflict) return res.status(404).json({ error: "Conflict not found." }); const updated = await resolveResearchConflict(prisma, { conflictId: conflict.id, status: req.body?.status, resolution: req.body?.resolution }); res.json({ conflict: updated }); } catch (error) { console.error(`POST /api/projects/${req.params.id}/research/conflicts/${req.params.id}/resolve failed:`, error); res.status(500).json({ error: "Failed to resolve the research conflict." }); } });
router.get("/:id/setup/suggestions", async (req, res) => { try { const project = await prisma.project.findUnique({ where: { id: req.params.id } }); if (!project) return res.status(404).json({ error: "Project not found." }); if (!project.researchSummary) return res.status(409).json({ error: "Research is not ready yet." }); res.json({ suggestions: buildSetupSuggestions(project) }); } catch (error) { console.error("GET /api/projects/:id/setup/suggestions failed:", error); res.status(500).json({ error: "Failed to build setup suggestions." }); } });
router.post("/:id/setup", async (req, res) => { try { const project = await prisma.project.findUnique({ where: { id: req.params.id } }); if (!project) return res.status(404).json({ error: "Project not found." }); if (!project.researchSummary) return res.status(409).json({ error: "Complete research before setup." }); const validation = validateSetup(req.body); if (validation.error) return res.status(400).json({ error: validation.error }); const { length, framework, tone, audienceLevel } = validation.value; const suggestions = buildSetupSuggestions(project); if (suggestions.framework.guardrailApplied && framework === "disruptor") return res.status(400).json({ error: "The Disruptor is blocked for this signal because of a high monetization-risk flag. Choose a safer framework." }); const updated = await prisma.project.update({ where: { id: project.id }, data: { scriptLengthSeconds: length, selectedFramework: framework, frameworkReasoning: suggestions.framework.reasoning, tone, audienceLevel, status: "storyboard" } }); res.json({ project: publicProject(updated, researchJobs.get(updated.id)), suggestions }); } catch (error) { console.error("POST /api/projects/:id/setup failed:", error); res.status(500).json({ error: "Failed to save setup choices." }); } });
router.post("/:id/publish-facebook", async (req, res) => { try { const project = await prisma.project.findUnique({ where: { id: req.params.id } }); if (!project) return res.status(404).json({ error: "Project not found." }); if (!project.renderUrl) return res.status(409).json({ error: "Render the final MP4 before publishing to Facebook." }); const result = await publishFacebookReel({ project, title: req.body?.title || project.title, description: req.body?.description || project.seoCaption || project.title }); await prisma.project.update({ where: { id: project.id }, data: { status: "published" } }); res.status(201).json({ projectId: project.id, ...result }); } catch (error) { console.error(`POST /api/projects/${req.params.id}/publish-facebook failed:`, error); const status = error.status === 401 || error.status === 403 ? 502 : error.status === 409 ? 409 : 503; res.status(status).json({ error: error.message || "Facebook publishing failed." }); } });
export default router;
