import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Header from "../components/Header";
import { useAuth } from "../context/AuthContext";
import "../components/ui.css";
import "./EditorPage.css";

const TRACK_ORDER = ["video", "narration", "captions", "overlays"];
const FRAME_SNAP = 1 / 30;
const GRID_SNAP = 0.25;
const SNAP_THRESHOLD = 0.14;
const formatTime = (seconds) => { const total = Math.max(0, Number(seconds || 0)); const minutes = Math.floor(total / 60); const secs = Math.floor(total % 60); const ms = Math.round((total - Math.floor(total)) * 10); return `${String(minutes).padStart(2, "0")}:${String(secs).padStart(2, "0")}.${ms}`; };
const cloneTimeline = (timeline) => JSON.parse(JSON.stringify(timeline));
const updateTrack = (timeline, trackId, updater) => ({ ...timeline, tracks: timeline.tracks.map((track) => track.id === trackId ? updater(track) : track) });
const clamp = (value, min, max) => Math.min(max, Math.max(min, value));
function snapTime(value, timeline, mode) { const numeric = Math.max(0, Number(value) || 0); const candidates = [mode === "frame" ? Math.round(numeric / FRAME_SNAP) * FRAME_SNAP : Math.round(numeric / GRID_SNAP) * GRID_SNAP, 0, Number(timeline?.duration || 0)]; for (const track of timeline?.tracks || []) for (const clip of track.clips || []) candidates.push(clip.start, clip.start + clip.duration); let best = numeric; let distance = SNAP_THRESHOLD; for (const candidate of candidates) { if (Math.abs(candidate - numeric) < distance) { best = candidate; distance = Math.abs(candidate - numeric); } } return Number(best.toFixed(3)); }

export default function EditorPage() {
  const { id } = useParams(); const { user } = useAuth();
  const [project, setProject] = useState(null); const [scenes, setScenes] = useState([]); const [timeline, setTimeline] = useState(null); const [version, setVersion] = useState(1);
  const [selectedClip, setSelectedClip] = useState({ trackId: "video", clipId: "" }); const [status, setStatus] = useState("loading"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false);
  const [playhead, setPlayhead] = useState(0); const [isPlaying, setIsPlaying] = useState(false); const [zoom, setZoom] = useState(80); const [history, setHistory] = useState([]); const [future, setFuture] = useState([]); const [snapMode, setSnapMode] = useState("grid");
  const saveTimer = useRef(null); const videoRef = useRef(null); const timelineRef = useRef(null);

  const loadEditor = useCallback(async () => {
    setStatus("loading"); setMessage(""); setDirty(false); setHistory([]); setFuture([]);
    try { const response = await fetch(`/api/projects/${id}/editor`, { cache: "no-store", credentials: "include" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Failed to load editor."); setProject(data.project); setScenes(data.scenes || []); setTimeline(data.editor.timeline); setVersion(data.editor.version); const firstVideo = data.editor.timeline?.tracks?.find((track) => track.id === "video")?.clips?.[0]; setSelectedClip({ trackId: "video", clipId: firstVideo?.id || "" }); setPlayhead(firstVideo?.start || 0); setStatus("ready"); } catch (error) { setStatus("error"); setMessage(error.message || "Failed to load editor."); }
  }, [id]);
  useEffect(() => { if (user) void loadEditor(); }, [loadEditor, user]);
  useEffect(() => () => { if (saveTimer.current) window.clearTimeout(saveTimer.current); }, []);
  useEffect(() => { timelineRef.current = timeline; }, [timeline]);

  const selected = useMemo(() => { if (!timeline || !selectedClip.clipId) return null; for (const track of timeline.tracks || []) { const clip = track.clips?.find((item) => item.id === selectedClip.clipId); if (clip) return { ...clip, trackId: track.id, trackName: track.name }; } return null; }, [timeline, selectedClip]);
  const selectedVideo = useMemo(() => timeline?.tracks?.find((track) => track.id === "video")?.clips?.find((item) => item.id === selectedClip.clipId) || timeline?.tracks?.find((track) => track.id === "video")?.clips?.[0] || null, [timeline, selectedClip]);
  const selectedScene = useMemo(() => scenes.find((scene) => scene.id === selectedVideo?.sourceId) || null, [scenes, selectedVideo]);

  useEffect(() => { if (!selectedVideo?.src || !videoRef.current) return; const local = clamp(playhead - Number(selectedVideo.start || 0), 0, Number(selectedVideo.duration || 0)); const target = Number(selectedVideo.offset || 0) + local; if (Math.abs(videoRef.current.currentTime - target) > 0.08) videoRef.current.currentTime = target; }, [playhead, selectedVideo]);
  useEffect(() => { if (!isPlaying) return undefined; const timer = window.setInterval(() => setPlayhead((current) => { const next = Number((current + FRAME_SNAP).toFixed(3)); if (next >= Number(timeline?.duration || 0)) { setIsPlaying(false); return Number(timeline?.duration || 0); } return next; }), 1000 / 30); return () => window.clearInterval(timer); }, [isPlaying, timeline?.duration]);

  const saveTimeline = useCallback(async (nextTimeline = timeline) => {
    if (!nextTimeline || saving) return; setSaving(true); setMessage("Saving…");
    try { const response = await fetch(`/api/projects/${id}/editor`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ version, timeline: nextTimeline }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Failed to save editor changes."); setVersion(data.editor.version); setTimeline(data.editor.timeline); setDirty(false); setMessage("Saved"); } catch (error) { setMessage(error.message || "Failed to save changes."); } finally { setSaving(false); }
  }, [id, timeline, saving, version]);
  useEffect(() => { if (!dirty || status !== "ready" || !timeline) return undefined; if (saveTimer.current) window.clearTimeout(saveTimer.current); saveTimer.current = window.setTimeout(() => { void saveTimeline(timeline); }, 900); return () => window.clearTimeout(saveTimer.current); }, [dirty, status, timeline, saveTimeline]);

  const mutate = useCallback((mutator, select, options = {}) => {
    const current = timelineRef.current;
    if (!current) return;
    const next = mutator(cloneTimeline(current));
    setHistory((items) => [...items.slice(-39), cloneTimeline(current)]);
    setFuture([]);
    setTimeline(next);
    setDirty(true); setMessage("Unsaved changes");
    if (select) setSelectedClip(select);
    if (typeof options.playhead === "number") setPlayhead(options.playhead);
  }, []);
  const undo = useCallback(() => { if (!timeline || !history.length) return; const previous = history[history.length - 1]; setFuture((items) => [cloneTimeline(timeline), ...items].slice(0, 40)); setHistory((items) => items.slice(0, -1)); setTimeline(previous); setDirty(true); setMessage("Undo · unsaved changes"); }, [history, timeline]);
  const redo = useCallback(() => { if (!timeline || !future.length) return; const next = future[0]; setHistory((items) => [...items.slice(-39), cloneTimeline(timeline)]); setFuture((items) => items.slice(1)); setTimeline(next); setDirty(true); setMessage("Redo · unsaved changes"); }, [future, timeline]);
  useEffect(() => { const onKeyDown = (event) => { const tag = event.target?.tagName; if (["INPUT", "TEXTAREA", "SELECT"].includes(tag) || event.target?.isContentEditable) return; const mod = event.ctrlKey || event.metaKey; if (mod && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); return; } if (mod && event.key.toLowerCase() === "y") { event.preventDefault(); redo(); return; } if (event.code === "Space") { event.preventDefault(); setIsPlaying((value) => !value); return; } if (event.key === "ArrowLeft") { event.preventDefault(); setPlayhead((value) => clamp(Number((value - FRAME_SNAP).toFixed(3)), 0, Number(timeline?.duration || 0))); } if (event.key === "ArrowRight") { event.preventDefault(); setPlayhead((value) => clamp(Number((value + FRAME_SNAP).toFixed(3)), 0, Number(timeline?.duration || 0))); } if (event.key.toLowerCase() === "s") splitClip(); if (event.key === "Delete" || event.key === "Backspace") deleteSelected(); }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); });

  function setClipValue(field, value) { if (!selected) return; const nextValue = field === "start" ? snapTime(value, timeline, snapMode) : Math.max(0.1, Number(value)); mutate((current) => updateTrack(current, selected.trackId, (track) => ({ ...track, clips: track.clips.map((clip) => clip.id === selected.id ? { ...clip, [field]: nextValue } : clip) })), undefined, { playhead: field === "start" ? nextValue : playhead }); }
  function moveClip(delta) { if (!selected || selected.trackId !== "video") return; mutate((current) => updateTrack(current, "video", (track) => { const index = track.clips.findIndex((clip) => clip.id === selected.id); const target = index + delta; if (index < 0 || target < 0 || target >= track.clips.length) return track; const clips = [...track.clips]; [clips[index], clips[target]] = [clips[target], clips[index]]; return { ...track, clips }; })); }
  function splitClip() { if (!selected) return; const splitAt = Number((selected.duration / 2).toFixed(3)); if (splitAt < 0.1) return; const firstId = `${selected.id}-a`; mutate((current) => updateTrack(current, selected.trackId, (track) => { const clips = []; for (const clip of track.clips) { if (clip.id !== selected.id) clips.push(clip); else clips.push({ ...clip, id: firstId, duration: splitAt }, { ...clip, id: `${selected.id}-b`, start: Number((clip.start + splitAt).toFixed(3)), duration: Number((clip.duration - splitAt).toFixed(3)), offset: Number(clip.offset || 0) + splitAt }); } return { ...track, clips }; }), { trackId: selected.trackId, clipId: firstId }, { playhead: selected.start }); }
  function deleteSelected() { if (!selected || selected.trackId === "narration") return; mutate((current) => updateTrack(current, selected.trackId, (track) => ({ ...track, clips: track.clips.filter((clip) => clip.id !== selected.id) })), { trackId: "video", clipId: "" }); }
  function addOverlay() { const overlayId = `overlay-${Date.now()}`; mutate((current) => updateTrack(current, "overlays", (track) => ({ ...track, clips: [...track.clips, { id: overlayId, type: "overlay", start: snapTime(playhead, current, snapMode), duration: 2, text: "New title", position: "center", style: "default" }] })), { trackId: "overlays", clipId: overlayId }, { playhead }); }
  function replaceVisual(asset) { if (!selected || selected.trackId !== "video" || !asset) return; mutate((current) => updateTrack(current, "video", (track) => ({ ...track, clips: track.clips.map((clip) => clip.id === selected.id ? { ...clip, assetId: asset.id, src: asset.videoUrl, thumbnailUrl: asset.thumbnailUrl } : clip) }))); }
  function selectClip(trackId, clipId) { const clip = timeline?.tracks?.find((track) => track.id === trackId)?.clips?.find((item) => item.id === clipId); setSelectedClip({ trackId, clipId }); if (clip) setPlayhead(Number(clip.start || 0)); setIsPlaying(false); }
  function seekTo(value) { setPlayhead(Number(clamp(snapTime(value, timeline, snapMode), 0, Number(timeline?.duration || 0)).toFixed(3))); setIsPlaying(false); }

  if (!user) return null;
  if (status === "loading") return <div className="hx-page"><Header /><main className="container editor-page"><div className="editor-state">Loading your editor…</div></main></div>;
  if (status === "error") return <div className="hx-page"><Header right={<Link to="/my-research" className="btn btn-ghost">My Research</Link>} /><main className="container editor-page"><div className="editor-state editor-state--error"><strong>Editor couldn't load.</strong><span>{message}</span><button className="btn btn-cream" onClick={loadEditor}>Retry</button></div></main></div>;

  const duration = Number(timeline?.duration || 0); const timelineWidth = Math.max(760, duration * zoom);
  return <div className="hx-page editor-page-shell"><Header right={<Link to={`/storyboard/${id}?stage=preview`} className="btn btn-ghost">Back to project</Link>} /><main className="container editor-page">
    <div className="editor-head"><div><p className="eyebrow">Advanced editor · non-destructive</p><h1>{project?.title || "Untitled project"}</h1><p>Independent timeline. Your Storyboard, narration and source media stay unchanged.</p></div><div className="editor-head__actions"><span className="editor-save-state">{saving ? "Saving…" : message || `Version ${version}`}</span><button className="btn btn-cream" type="button" onClick={() => void saveTimeline()} disabled={saving || !dirty}>{saving ? "Saving…" : "Save changes"}</button></div></div>
    <section className="editor-workspace"><div className="editor-preview-panel"><div className="editor-preview-frame">{selectedVideo?.src ? <video ref={videoRef} key={`${selectedVideo.id}-${selectedVideo.src}`} src={selectedVideo.src} poster={selectedVideo.thumbnailUrl || undefined} controls playsInline /> : <div className="editor-preview-empty">No visual selected</div>}{selectedVideo?.title && <div className="editor-preview-title">{selectedVideo.title}</div>}</div><div className="editor-preview-controls"><button type="button" className="btn btn-ghost" onClick={() => setIsPlaying((value) => !value)}>{isPlaying ? "Pause" : "Play"}</button><input aria-label="Playhead" type="range" min="0" max={duration || 1} step={FRAME_SNAP} value={clamp(playhead, 0, duration || 1)} onChange={(event) => seekTo(Number(event.target.value))} /><span className="editor-timecode">{formatTime(playhead)} / {formatTime(duration)}</span></div><div className="editor-preview-meta"><span>{formatTime(duration)}</span><span>1080 × 1920 · {timeline?.fps || 30} fps</span></div></div>
      <aside className="editor-inspector"><div className="editor-panel-heading"><span>Inspector</span><span className="mono-label">{selected?.trackName || "Nothing selected"}</span></div>{!selected && <div className="editor-inspector__empty">Select a clip on the timeline to edit it.</div>}{selected && <div className="editor-inspector__form"><label>Start<input type="number" min="0" step={FRAME_SNAP} value={selected.start} onChange={(event) => setClipValue("start", Number(event.target.value))} /></label><label>Duration<input type="number" min="0.1" step={FRAME_SNAP} value={selected.duration} onChange={(event) => setClipValue("duration", Number(event.target.value))} /></label>{selected.trackId === "video" && selectedScene?.assets?.length > 0 && <label>Replace visual<select value={selected.assetId || ""} onChange={(event) => replaceVisual(selectedScene.assets.find((asset) => asset.id === event.target.value))}><option value="">Current visual</option>{selectedScene.assets.map((asset) => <option key={asset.id} value={asset.id}>Visual {asset.sortOrder + 1}</option>)}</select></label>}{selected.type === "audio" && <label>Volume<input type="number" min="0" max="2" step="0.05" value={selected.volume ?? 1} onChange={(event) => setClipValue("volume", Number(event.target.value))} /></label>}{selected.type === "caption" && <label>Caption text<textarea value={selected.text || ""} onChange={(event) => setClipValue("text", event.target.value)} rows="5" /></label>}{selected.type === "overlay" && <label>Overlay text<textarea value={selected.text || ""} onChange={(event) => setClipValue("text", event.target.value)} rows="4" /></label>}<div className="editor-inspector__buttons"><button className="btn btn-ghost" onClick={() => moveClip(-1)} disabled={selected.trackId !== "video"}>Move left</button><button className="btn btn-ghost" onClick={() => moveClip(1)} disabled={selected.trackId !== "video"}>Move right</button><button className="btn btn-ghost" onClick={splitClip}>Split</button><button className="btn btn-danger" onClick={deleteSelected} disabled={selected.trackId === "narration"}>Delete</button></div></div>}<button className="btn btn-ghost editor-add-overlay" onClick={addOverlay}>+ Add text overlay</button></aside>
    </section>
    <section className="editor-timeline-panel"><div className="editor-timeline-toolbar"><div><strong>Timeline</strong><span>{formatTime(duration)} total · Playhead {formatTime(playhead)}</span></div><div className="editor-timeline-toolbar__actions"><button className="btn btn-ghost" type="button" onClick={undo} disabled={!history.length}>Undo</button><button className="btn btn-ghost" type="button" onClick={redo} disabled={!future.length}>Redo</button><label className="editor-zoom">Zoom <input type="range" min="50" max="160" step="10" value={zoom} onChange={(event) => setZoom(Number(event.target.value))} /></label><label className="editor-snap">Snap <select value={snapMode} onChange={(event) => setSnapMode(event.target.value)}><option value="grid">0.25s + clip</option><option value="frame">Frame + clip</option></select></label></div></div><div className="editor-timeline-scroll"><div className="editor-timeline-ruler" style={{ minWidth: `${timelineWidth}px` }} onClick={(event) => { const rect = event.currentTarget.getBoundingClientRect(); seekTo((event.clientX - rect.left) / zoom); }}>{Array.from({ length: Math.max(2, Math.ceil(duration / 5) + 1) }).map((_, index) => <span key={index} style={{ left: `${index * 5 * zoom}px` }}>{formatTime(index * 5)}</span>)}<i className="editor-playhead" style={{ left: `${playhead * zoom}px` }} /></div><div className="editor-tracks" style={{ minWidth: `${timelineWidth}px` }}>{TRACK_ORDER.map((trackId) => { const track = timeline?.tracks?.find((item) => item.id === trackId); if (!track) return null; return <div className="editor-track" key={track.id}><div className="editor-track-label"><strong>{track.name}</strong><span>{track.clips.length} clips</span></div><div className="editor-track-lane">{track.clips.map((clip) => <button key={clip.id} type="button" className={`editor-clip editor-clip--${track.kind} ${selectedClip.clipId === clip.id ? "is-selected" : ""}`} style={{ left: `${clip.start * zoom}px`, width: `${Math.max(56, clip.duration * zoom)}px` }} onClick={() => selectClip(track.id, clip.id)}><span>{clip.title || clip.text || clip.type}</span><small>{formatTime(clip.duration)}</small></button>)}<i className="editor-playhead" style={{ left: `${playhead * zoom}px` }} /></div></div>; })}</div></div><div className="editor-shortcuts"><span>Space Play/Pause</span><span>← → Frame</span><span>S Split</span><span>Delete Remove</span><span>⌘/Ctrl Z Undo</span><span>⇧⌘/Ctrl Z Redo</span></div></section>
  </main></div>;
}
