import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import "../components/ui.css";

export default function ReviewPage() {
  const { token } = useParams(); const [review, setReview] = useState(null); const [name, setName] = useState(""); const [body, setBody] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { const response = await fetch(`/api/projects/review/${token}`); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Review link is unavailable."); setReview(data.review); }
  useEffect(() => { load().catch((e) => setError(e.message)); }, [token]);
  async function comment(event) { event.preventDefault(); setError(""); setMessage(""); const response = await fetch(`/api/projects/review/${token}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ authorName: name, body }) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setError(data.error || "Unable to post comment."); setBody(""); setMessage("Comment added."); await load(); }
  if (error && !review) return <div className="hx-page"><main className="container" style={{ maxWidth: 760, padding: 60 }}><h1>Review unavailable</h1><p>{error}</p></main></div>;
  return <div className="hx-page"><main className="container" style={{ maxWidth: 900, padding: "60px 0" }}><p className="eyebrow">Helix · review</p><h1>{review?.project?.title || "Project review"}</h1><p>This is a read-only review workspace. The project owner controls the editor; reviewers can leave feedback below.</p><section className="hx-card" style={{ marginTop: 20, padding: 24 }}><h2>Timeline</h2><p><strong>Editor version:</strong> {review?.project?.editor?.version ?? "—"}</p><p><strong>Duration:</strong> {Number(review?.project?.durationSeconds || review?.project?.editor?.timeline?.duration || 0).toFixed(2)}s</p><p>{review?.project?.editor?.timeline?.tracks?.length || 0} timeline tracks are available to the owner.</p></section><section className="hx-card" style={{ marginTop: 16, padding: 24 }}><h2>Comments</h2>{(review?.comments || []).map((item) => <div key={item.id} style={{ borderBottom: "1px solid var(--border-color, #ddd)", padding: "12px 0" }}><strong>{item.authorName}</strong>{item.resolved ? " · Resolved" : ""}<p style={{ whiteSpace: "pre-wrap" }}>{item.body}</p></div>)}{!review?.comments?.length && <p>No comments yet.</p>}<form onSubmit={comment} style={{ marginTop: 18, display: "grid", gap: 10 }}><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Your name" maxLength={120} /><textarea value={body} onChange={(e) => setBody(e.target.value)} placeholder="Leave review feedback…" rows={4} maxLength={2000} required /><button className="btn btn-cream" type="submit">Add comment</button></form>{message && <p>{message}</p>}{error && <p role="alert">{error}</p>}</section></main></div>;
}
