import cors from "cors";
import express from "express";
import path from "node:path";
import signalsRouter from "./routes/signals.js";
import projectsRouter from "./routes/projects.js";
import storyboardRouter from "./routes/storyboard.js";
import renderRouter from "./routes/render.js";
import exportRouter from "./routes/export.js";

const app = express();
app.use(cors());
app.use(express.json());
app.get("/api/health", (_req, res) => res.json({ ok: true }));
app.use("/api/signals", signalsRouter);
app.use("/api/projects", projectsRouter);
app.use("/api/audio", express.static(path.resolve(process.cwd(), "storage", "audio"), { fallthrough: false, maxAge: "1h" }));
app.use("/api/render-assets", express.static(path.resolve(process.cwd(), "storage", "render-assets"), { fallthrough: false, maxAge: "1h" }));
app.use("/api/render-files", express.static(path.resolve(process.cwd(), "storage", "renders"), { fallthrough: false, maxAge: "1h" }));
app.use("/api/export-files", express.static(path.resolve(process.cwd(), "storage", "exports"), { fallthrough: false, maxAge: "1h" }));
app.use("/api", renderRouter);
app.use("/api", storyboardRouter);
app.use("/api", exportRouter);
app.use("/api", (_req, res) => res.status(404).json({ error: "Not found." }));
export default app;
