const PREDEFINED_VOICES = [
  {
    id: "kokoro-af-heart",
    name: "Heart",
    engine: "kokoro",
    voice: "af_heart",
    language: "English",
    accent: "American",
    gender: "Female",
    tone: "Warm",
    description: "Warm, natural, and versatile",
  },
  {
    id: "kokoro-af-sarah",
    name: "Sarah",
    engine: "kokoro",
    voice: "af_sarah",
    language: "English",
    accent: "American",
    gender: "Female",
    tone: "Conversational",
    description: "Casual and approachable",
  },
  {
    id: "kokoro-af-nicole",
    name: "Nicole",
    engine: "kokoro",
    voice: "af_nicole",
    language: "English",
    accent: "American",
    gender: "Female",
    tone: "Friendly",
    description: "Friendly and easy to follow",
  },
  {
    id: "kokoro-af-nova",
    name: "Nova",
    engine: "kokoro",
    voice: "af_nova",
    language: "English",
    accent: "American",
    gender: "Female",
    tone: "Modern",
    description: "Clear and contemporary",
  },
  {
    id: "kokoro-af-jessica",
    name: "Jessica",
    engine: "kokoro",
    voice: "af_jessica",
    language: "English",
    accent: "American",
    gender: "Female",
    tone: "Energetic",
    description: "Energetic and expressive",
  },
  {
    id: "kokoro-am-adam",
    name: "Adam",
    engine: "kokoro",
    voice: "am_adam",
    language: "English",
    accent: "American",
    gender: "Male",
    tone: "Confident",
    description: "Strong and confident",
  },
  {
    id: "kokoro-am-michael",
    name: "Michael",
    engine: "kokoro",
    voice: "am_michael",
    language: "English",
    accent: "American",
    gender: "Male",
    tone: "Warm",
    description: "Warm and trustworthy",
  },
  {
    id: "kokoro-am-liam",
    name: "Liam",
    engine: "kokoro",
    voice: "am_liam",
    language: "English",
    accent: "American",
    gender: "Male",
    tone: "Conversational",
    description: "Friendly and conversational",
  },
  {
    id: "kokoro-am-eric",
    name: "Eric",
    engine: "kokoro",
    voice: "am_eric",
    language: "English",
    accent: "American",
    gender: "Male",
    tone: "Authoritative",
    description: "Professional and authoritative",
  },
  {
    id: "kokoro-am-puck",
    name: "Puck",
    engine: "kokoro",
    voice: "am_puck",
    language: "English",
    accent: "American",
    gender: "Male",
    tone: "Playful",
    description: "Playful and expressive",
  },
  {
    id: "kokoro-bf-emma",
    name: "Emma",
    engine: "kokoro",
    voice: "bf_emma",
    language: "English",
    accent: "British",
    gender: "Female",
    tone: "Professional",
    description: "Warm and professional",
  },
  {
    id: "kokoro-bf-alice",
    name: "Alice",
    engine: "kokoro",
    voice: "bf_alice",
    language: "English",
    accent: "British",
    gender: "Female",
    tone: "Refined",
    description: "Refined and elegant",
  },
  {
    id: "kokoro-bf-isabella",
    name: "Isabella",
    engine: "kokoro",
    voice: "bf_isabella",
    language: "English",
    accent: "British",
    gender: "Female",
    tone: "Sophisticated",
    description: "Sophisticated and clear",
  },
  {
    id: "kokoro-bm-fable",
    name: "Fable",
    engine: "kokoro",
    voice: "bm_fable",
    language: "English",
    accent: "British",
    gender: "Male",
    tone: "Storytelling",
    description: "Storytelling and engaging",
  },
  {
    id: "kokoro-bm-george",
    name: "George",
    engine: "kokoro",
    voice: "bm_george",
    language: "English",
    accent: "British",
    gender: "Male",
    tone: "Classic",
    description: "Classic British delivery",
  },
  {
    id: "kokoro-bm-lewis",
    name: "Lewis",
    engine: "kokoro",
    voice: "bm_lewis",
    language: "English",
    accent: "British",
    gender: "Male",
    tone: "Modern",
    description: "Modern British delivery",
  },
  {
    id: "kokoro-bm-daniel",
    name: "Daniel",
    engine: "kokoro",
    voice: "bm_daniel",
    language: "English",
    accent: "British",
    gender: "Male",
    tone: "Polished",
    description: "Polished and professional",
  },
];

export function getPredefinedVoices() {
  return PREDEFINED_VOICES.map((voice) => ({ ...voice }));
}

export function getPredefinedVoice(id) {
  const voice = PREDEFINED_VOICES.find((item) => item.id === String(id || "").trim());
  return voice ? { ...voice } : null;
}

export function getPredefinedVoiceFilters() {
  return {
    accents: [...new Set(PREDEFINED_VOICES.map((voice) => voice.accent))],
    genders: [...new Set(PREDEFINED_VOICES.map((voice) => voice.gender))],
    tones: [...new Set(PREDEFINED_VOICES.map((voice) => voice.tone))],
  };
}

export const PREDEFINED_VOICE_PREVIEW_TEXT =
  "Hi, this is a Helix narrator preview. This voice is available as a built-in narration option for your storyboard.";
